enabled_rules:
  - bitwarden_workflow_linter.rules.name_exists.RuleNameExists
  - bitwarden_workflow_linter.rules.name_capitalized.RuleNameCapitalized
  - bitwarden_workflow_linter.rules.pinned_job_runner.RuleJobRunnerVersionPinned
  - bitwarden_workflow_linter.rules.job_environment_prefix.RuleJobEnvironmentPrefix
  - bitwarden_workflow_linter.rules.step_pinned.RuleStepUsesPinned
  - bitwarden_workflow_linter.rules.underscore_outputs.RuleUnderscoreOutputs

approved_actions_path: default_actions.json
