enabled_rules:
    - id: bitwarden_workflow_linter.rules.name_exists.RuleNameExists
      level: error
    - id: bitwarden_workflow_linter.rules.name_capitalized.RuleNameCapitalized
      level: error
    - id: bitwarden_workflow_linter.rules.pinned_job_runner.RuleJobRunnerVersionPinned
      level: error
    - id: bitwarden_workflow_linter.rules.job_environment_prefix.RuleJobEnvironmentPrefix
      level: error
    - id: bitwarden_workflow_linter.rules.step_approved.RuleStepUsesApproved
      level: error
    - id: bitwarden_workflow_linter.rules.step_pinned.RuleStepUsesPinned
      level: error
    - id: bitwarden_workflow_linter.rules.underscore_outputs.RuleUnderscoreOutputs
      level: warning
    - id: bitwarden_workflow_linter.rules.run_actionlint.RunActionlint
      level: error
    - id: bitwarden_workflow_linter.rules.check_pr_target.RuleCheckPrTarget
      level: error
    - id: bitwarden_workflow_linter.rules.permissions_exist.RulePermissionsExist
      level: error
    - id: bitwarden_workflow_linter.rules.check_blocked_domains.RuleCheckBlockedDomains
      level: warning
    - id: bitwarden_workflow_linter.rules.run_zizmor.RunZizmor
      level: warning

approved_actions_path: default_actions.json
default_branch: main

# List of domains that should trigger an error if found in workflows
blocked_domains:
    - ghrc.io
# Optional: URL to zizmor configuration file
zizmor_config_url: https://raw.githubusercontent.com/bitwarden/workflow-linter/refs/heads/main/zizmor.yml
